### ISSUE TITLE
(Minor Issue) Crash when clicking license button in settings

### ISSUE THREAD

**Issue by osjasmine** [svenjacobs/leon#78]
Leon crashes immediately when I press the license button
Logs from logcat (not sure if they are directly relevant):
```java
FATAL EXCEPTION: main
Process: com.svenjacobs.app.leon, PID: 15058
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/material/MaterialTheme;
	at r3.i.b(Unknown Source:6)
	at r3.e.c(SourceFile:2)
	at w4.a$a.Q(SourceFile:78)
	at m0.a.a(SourceFile:50)
	at m0.a.Q(Unknown Source:8)
	at d0.d1.R(SourceFile:147)
	at m0.a.R(SourceFile:58)
	at j1.t.R(SourceFile:59)
	at m0.a.R(SourceFile:58)
	at f0.m.y(SourceFile:23)
	at b0.a.l0(SourceFile:43)
	at f0.h.O(SourceFile:129)
	at f0.h.K(Unknown Source:13)
	at f0.h0.t(SourceFile:18)
	at f0.z1.a(SourceFile:45)
	at f0.h$b.a(SourceFile:10)
	at f0.h$b.a(SourceFile:10)
	at f0.h0.s(Unknown Source:12)
	at j1.q.c(SourceFile:110)
	at j1.q$b.g0(SourceFile:130)
	at d0.f1.V(SourceFile:812)
	at j1.z.f(SourceFile:38)
	at j1.r$a.f(SourceFile:9)
	at l1.z$b$a.y(SourceFile:103)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.w(SourceFile:117)
	at l1.n.t0(SourceFile:127)
	at j1.i0$a.d(SourceFile:33)
	at l1.z$b$b.y(SourceFile:20)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.z0(SourceFile:61)
	at l1.z$b.t0(SourceFile:41)
	at j1.i0$a.d(SourceFile:33)
	at t.g.b(SourceFile:46)
	at t.h$b.V(SourceFile:25)
	at j1.z.f(SourceFile:38)
	at l1.z$b$a.y(SourceFile:103)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.w(SourceFile:117)
	at l1.n.t0(SourceFile:127)
	at j1.i0$a.h(SourceFile:53)
	at v0.g0$a.V(SourceFile:18)
	at j1.z.f(SourceFile:38)
	at l1.t.t0(SourceFile:45)
	at j1.i0$a.f(SourceFile:75)
	at t.p$a.V(SourceFile:11)
	at j1.z.f(SourceFile:38)
	at l1.t.t0(SourceFile:45)
	at j1.i0$a.d(SourceFile:33)
	at l1.z$b$b.y(SourceFile:20)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.z0(SourceFile:61)
	at l1.z$b.t0(SourceFile:41)
	at j1.i0$a.d(SourceFile:33)
	at t.g.b(SourceFile:46)
	at t.h$b.V(SourceFile:25)
	at j1.z.f(SourceFile:38)
	at l1.z$b$a.y(SourceFile:103)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.w(SourceFile:117)
	at l1.n.t0(SourceFile:127)
	at j1.i0$a.h(SourceFile:53)
	at v0.k$a.V(SourceFile:18)
	at j1.z.f(SourceFile:38)
	at l1.t.t0(SourceFile:45)
	at j1.i0$a.d(SourceFile:33)
	at l1.z$b$b.y(SourceFile:20)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.z0(SourceFile:61)
	at l1.z$b.t0(SourceFile:41)
	at j1.i0$a.d(SourceFile:33)
	at t.g.b(SourceFile:46)
	at t.h$c.V(SourceFile:48)
	at j1.z.f(SourceFile:38)
	at l1.z$b$a.y(SourceFile:103)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.w(SourceFile:117)
	at l1.n.t0(SourceFile:127)
	at j1.i0$a.d(SourceFile:33)
	at l1.z$b$b.y(SourceFile:20)
	at o0.h$a.a(SourceFile:64)
	at o0.w$c.y(SourceFile:7)
	at b0.a.l0(SourceFile:43)
	at o0.w.c(SourceFile:75)
	at l1.x0.a(Unknown Source:12)
	at l1.z$b.z0(SourceFile:61)
	at l1.v.N(SourceFile:27)
	at l1.e0.l(SourceFile:197)
	at l1.e0.h(SourceFile:63)
	at androidx.compose.ui.platform.AndroidComposeView.c(SourceFile:14)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:22)
	at android.view.View.draw(View.java:23194)
	at android.view.View.updateDisplayListIfDirty(View.java:22066)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
```

```java
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
	at android.view.View.updateDisplayListIfDirty(View.java:22021)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4264)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4048)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3321)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2201)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9000)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.ClassNotFoundException: androidx.compose.material.MaterialTheme
	... 152 more

```

Android 10 - Samsung A10 (One UI 2.0) 
Leon 1.2.0 (Fdroid)

**Comment by svenjacobs** [comment]
Thanks for the report!

I can reproduce this with a `release` build but not with a `debug` build. I first had ProGuard/R8 in mind but even when minification/obfuscation is disabled, it still crashes with a `release` build.

Leon uses Material 3 while [AboutLibraries](https://github.com/mikepenz/AboutLibraries) still uses Material 2. Maybe this is an issue? Also even if this is fixed, there currently is [this crash](https://github.com/mikepenz/AboutLibraries/issues/796) when clicking on a library.

**Comment by svenjacobs** [comment]
Leon depends on Marerial 3 `1.0.0-rc01` which depends on Compose `1.3.0-rc01`. A downgrade is not easily possible. I guess we have to wait until AboutLibraries supports Compose 1.3.0.

**Comment by svenjacobs** [comment]
This has been fixed and is available in [v17](https://github.com/svenjacobs/leon/releases/tag/v17).
